script:
  - bundle
  - bundle exec rspec
os:
  - linux
  - osx
rvm:
  - 2.0
  - 2.1
  - 2.2
matrix:
  exclude:
    - rvm: 2.2
      os: osx
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - gem install bundler
