# Use the new container-based Travis infrastructure.
sudo: false

language: ruby
cache:
  - bundler
before_install:
  - gem install bundler
script:
  - bundle
  - bundle exec rspec
os:
  - linux
  - osx
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2.3
  - ruby-head
  - jruby-19mode
matrix:
  exclude:
    - rvm: ruby-head
      os: osx
    - rvm: jruby-19mode
      os: osx

notifications:
  email:
    on_success: always
    on_failure: always
