# Use the new container-based Travis infrastructure.
sudo: false

language: ruby
cache:
  - bundler
before_install:
  - gem install bundler
script:
  - bundle
  - bundle exec rspec
os:
  - linux
  - osx
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode

notifications:
  email:
    on_success: always
    on_failure: always
